instrument: XAU_USD
alignmentTimezone: America/New_York
dailyAlignment: 17
windows:
  sma_fast: 50
  sma_slow: 200
  rsi: 14
  atr: 14
report:
  filename: out/xau_report_daily.md
  include_intraday: false
  intraday_granularities: []
thresholds:
  rsi_overbought: 70
  rsi_oversold: 30
  near_pct: 0.001
