name: btc-daily

on:
  schedule:
    - cron: "0 14 * * 1-5"
  workflow_dispatch: {}

permissions:
  contents: read

env:
  FEISHU_WEBHOOK_ALERTS: ${{ secrets.FEISHU_WEBHOOK_ALERTS }}
  FEISHU_SECRET_ALERTS: ${{ secrets.FEISHU_SECRET_ALERTS }}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install uv
        run: pipx install uv
      - name: Sync deps
        run: uv sync --locked --no-dev || uv sync --no-dev

      - name: Guard 07:00–07:10 PT window
        env:
          TZ: America/Los_Angeles
          WINDOW_START: "0700"
          WINDOW_END: "0710"
        run: |
          now=$(TZ=$TZ date +%H%M)
          if [ "$now" -lt "$WINDOW_START" ] || [ "$now" -gt "$WINDOW_END" ]; then
            echo "非播报窗口，退出。"; exit 0; fi

      - name: Refresh 1d
        run: uv run dm btc fetch --interval 1d --lookback 10d
      - name: Refresh 1h
        run: uv run dm btc fetch --interval 1h --lookback 5d
      - name: Refresh 1m
        run: uv run dm btc fetch --interval 1m --lookback 2d

      - name: Generate BTC report
        run: uv run dm btc report --out out/btc_report.md

      - name: Push Feishu (alerts)
        run: |
          uv run python -m daily_messenger.tools.post_feishu \
            --channel alerts --mode post --summary out/btc_report.md
