name: btc-d

on:
  schedule:
    - cron: "0 10 * * 1-5"   # 18:00 Asia/Shanghai
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: btc-d
  cancel-in-progress: true

env:
  PYTHON_VERSION: "3.11"

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      FEISHU_WEBHOOK_DAILY: ${{ secrets.FEISHU_WEBHOOK_DAILY }}
      FEISHU_SECRET_DAILY: ${{ secrets.FEISHU_SECRET_DAILY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Sync dependencies
        run: uv sync --locked --no-dev || uv sync --no-dev

      - name: Prepare BTC data dir
        run: mkdir -p out/btc

      - name: Restore BTC klines cache
        uses: actions/cache/restore@v4
        with:
          path: out/btc
          key: btc-klines-${{ runner.os }}-${{ github.ref_name }}
          restore-keys: |
            btc-klines-${{ runner.os }}-${{ github.ref_name }}-
            btc-klines-${{ runner.os }}-

      - name: Guard 18:00–18:10 Asia/Shanghai window
        if: ${{ github.event_name == 'schedule' }}
        env:
          TZ: Asia/Shanghai
          WINDOW_START: "1800"
          WINDOW_END: "1810"
        run: |
          now=$(TZ=$TZ date +%H%M)
          if [ "$now" -lt "$WINDOW_START" ] || [ "$now" -gt "$WINDOW_END" ]; then
            echo "当前不在 BTC 日报窗口（Asia/Shanghai 18:00–18:10），提前退出。"
            exit 0
          fi

      - name: Refresh BTC 1d data (>=260 bars)
        run: uv run dm btc fetch --interval 1d --lookback 400d

      - name: Generate BTC daily report
        run: |
          uv run dm btc report \
            --config config/ta_btc_daily.yml \
            --out out/btc_report_daily.md

      - name: Save BTC klines cache
        if: success()
        uses: actions/cache/save@v4
        with:
          path: out/btc
          key: btc-klines-${{ runner.os }}-${{ github.ref_name }}-${{ github.run_id }}

      - name: Push Feishu daily channel
        if: ${{ env.FEISHU_WEBHOOK_DAILY != '' }}
        run: |
          uv run python -m daily_messenger.tools.post_feishu \
            --channel daily \
            --mode post \
            --summary out/btc_report_daily.md \
            --title "BTC/USDT 每日技术摘要"
