name: daily-digest

on:
  schedule:
    - cron: "0 14 * * 1-5"
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: daily-digest
  cancel-in-progress: true

env:
  PYTHON_VERSION: "3.11"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Sync dependencies
        run: uv sync --locked --no-dev

      - name: Guard 07:00–07:10 PT window
        if: ${{ github.event_name == 'schedule' }}
        env:
          TZ: America/Los_Angeles
          WINDOW_START: "0700"
          WINDOW_END: "0710"
        run: |
          now=$(TZ=$TZ date +%H%M)
          if [ "$now" -lt "$WINDOW_START" ] || [ "$now" -gt "$WINDOW_END" ]; then
            echo "当前不在播报窗口，提前结束。"
            exit 0
          fi

      - name: Run ETL
        id: etl
        continue-on-error: true
        env:
          API_KEYS: ${{ secrets.API_KEYS }}
        run: uv run python -m daily_messenger.etl.run_fetch

      - name: Run scoring
        id: scoring
        continue-on-error: true
        run: uv run python -m daily_messenger.scoring.run_scores

      - name: Render digest
        id: digest
        run: |
          if [ "${{ steps.etl.outcome }}" != "success" ] || [ "${{ steps.scoring.outcome }}" != "success" ]; then
            echo "DEGRADED=1" >> $GITHUB_ENV
            uv run python -m daily_messenger.digest.make_daily --degraded
          else
            uv run python -m daily_messenger.digest.make_daily
          fi

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: out

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4

      - name: Push Feishu card
        if: always() && secrets.FEISHU_WEBHOOK != ''
        env:
          FEISHU_WEBHOOK: ${{ secrets.FEISHU_WEBHOOK }}
          FEISHU_SECRET: ${{ secrets.FEISHU_SECRET }}
        run: |
          uv run python -m daily_messenger.tools.post_feishu --webhook "$FEISHU_WEBHOOK" --summary out/digest_summary.txt --card out/digest_card.json

      - name: Mark failure when pipeline degraded
        if: ${{ steps.etl.outcome != 'success' || steps.scoring.outcome != 'success' }}
        run: exit 1
